# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz";
      sha256 = "0s14r1w2x9sdlcsw8mxiqgw4rz5zs5lpqpxrfyn4a1mkndqqbdrr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robotframework" = super.buildPythonPackage rec {
    pname = "robotframework";
    version = "2.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/9c/ffed110856b2c796f928e4fdba3a525873927a8e1c54c736b163d089939c/robotframework-2.8.2.tar.gz";
      sha256 = "0pvcpzibw00lam4dqd92y68ifml7bkbph32gk8spr6ili8qv676s";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zc.buildout" = super.buildPythonPackage rec {
    pname = "zc.buildout";
    version = "2.13.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/10/c1d4e7cf3659c048752395df34491d71bc38b474ff9f1be27931452c6080/zc.buildout-2.13.4-py2.py3-none-any.whl";
      sha256 = "0j06d3kc4pbayvai3jj57zj1ajzb7sp07lrb6zvqnjgzw4p3nk8p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
  "zc.recipe.egg" = super.buildPythonPackage rec {
    pname = "zc.recipe.egg";
    version = "2.0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/6f/c6871e8490a153c3b44ac43e4a6552d802561a12b4780c7ea088a7ec5ff0/zc.recipe.egg-2.0.7.tar.gz";
      sha256 = "1lz6yjavc7s01bqfn11sk05x0i935cbk312fpf23akk1g44v17mq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
      self."zc.buildout"
    ];
  };
  "zc.recipe.testrunner" = super.buildPythonPackage rec {
    pname = "zc.recipe.testrunner";
    version = "2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/09/9207fce4ae30d36272fa6d32637862646855594904f00c0097c24cd2d83b/zc.recipe.testrunner-2.2-py2.py3-none-any.whl";
      sha256 = "1x0j1r8b9chkp36m2ddpa1azdkspadp066yjw64wbnwqah105819";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
      self."zc.buildout"
      self."zc.recipe.egg"
      self."zope.testrunner"
    ];
  };
  "zope.exceptions" = super.buildPythonPackage rec {
    pname = "zope.exceptions";
    version = "4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/1a/55aac95b3fe46de512905af49189f055df1404147bcedb3fe81476597799/zope.exceptions-4.4-py2.py3-none-any.whl";
      sha256 = "0qdgyiz53g37zcxfa923rgvf0skdws3v9a0fjm25kghfx43wr65v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
      self."zope.interface"
    ];
  };
  "zope.interface" = super.buildPythonPackage rec {
    pname = "zope.interface";
    version = "5.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/58/e0877f58daa69126a5fb325d6df92b20b77431cd281e189c5ec42b722f58/zope.interface-5.4.0.tar.gz";
      sha256 = "03jsiad578392pfmxa1ihkmvdh2q3dcwqy1vv240jgzc1x9mzfjx";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
  "zope.testrunner" = super.buildPythonPackage rec {
    pname = "zope.testrunner";
    version = "5.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/34/a1d39bf879096db480d9f9b3b3c6719a597d1dfc9c5c55924a697c6f7894/zope.testrunner-5.3.0-py2.py3-none-any.whl";
      sha256 = "10kwcxp64av7zm1bcv8sgm12x7k5dlk5sa1br6a3p0kxb0zicga6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
      self."six"
      self."zope.exceptions"
      self."zope.interface"
    ];
  };
}
