name: "build"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [python27, python36, python37, python38, python39]
        robotframework: [2.8.2, 2.8.7, 2.9.2, 3.0.4, 3.1.2, 3.2.2, 4.0.3, 4.1.3]
        exclude:
          - python: python27
            robotframework: 5.0.0
          - python: python36
            robotframework: 2.8.2
          - python: python36
            robotframework: 2.8.7
          - python: python36
            robotframework: 2.9.2
          - python: python37
            robotframework: 2.8.2
          - python: python37
            robotframework: 2.8.7
          - python: python37
            robotframework: 2.9.2
          - python: python38
            robotframework: 2.8.2
          - python: python38
            robotframework: 2.8.7
          - python: python38
            robotframework: 2.9.2
          - python: python39
            robotframework: 2.8.2
          - python: python39
            robotframework: 2.8.7
          - python: python39
            robotframework: 2.9.2
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: datakurre
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: make nix-show nix-test PYTHON=${{ matrix.python }} RF=${{ matrix.robotframework }}
