name: "build"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [python39, python310, python311, python312]
        robotframework: [3.0.4, 3.1.2, 3.2.2, 4.0.3, 4.1.3, 5.0.1, 6.0.2, 6.1.1, 7.0.1, 7.1.1, 7.2.2]
        exclude:
          - python: python310
            robotframework: 3.0.4
          - python: python310
            robotframework: 3.1.2
          - python: python311
            robotframework: 3.0.4
          - python: python311
            robotframework: 3.1.2
          - python: python312
            robotframework: 3.0.4
          - python: python312
            robotframework: 3.1.2
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: datakurre
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix profile install nixpkgs#devenv
    - run: make devenv-show devenv-test PYTHON=${{ matrix.python }} RF=${{ matrix.robotframework }}
